{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;\f1\fnil\fcharset0 Menlo-Bold;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red125\green125\blue125;\red252\green30\blue98;
\red180\green36\blue25;\red159\green160\blue28;\red255\green255\blue255;\red99\green186\blue28;\red47\green180\blue29;
\red46\green174\blue187;}
{\*\expandedcolortbl;;\csgray\c0;\cssrgb\c56390\c56390\c56390;\cssrgb\c100000\c23390\c45833;
\cssrgb\c76411\c21697\c12527;\cssrgb\c68469\c68012\c14211;\csgray\c100000;\cssrgb\c45191\c76355\c14358;\cssrgb\c20241\c73898\c14950;
\cssrgb\c20199\c73241\c78251;}
{\info
{\author Rex Sears}
{\*\copyright Rex Sears}}\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs36 \cf2 \CocoaLigature0 Last login: Tue Sep 12 14:56:13 on ttys000\
\cf3 rextsears \cf4 ~ \cf2  $ cd code\
\cf3 rextsears \cf4 ~/code \cf2  $ createdb finchcollector\
createdb: error: database creation failed: ERROR:  database "finchcollector" already exists\
\cf3 rextsears \cf4 ~/code \cf2  $ django-admin startproject finchcollector\
\cf3 rextsears \cf4 ~/code \cf2  $ cd finchcollector\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ code .\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python3 manage.py startapp main_app\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python3 manage.py runserver\
Watching for file changes with StatReloader\
Performing system checks...\
\
System check identified no issues (0 silenced).\
\
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0
\cf5 You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\cf2 \
\cf5 Run 'python manage.py migrate' to apply them.\cf2 \
September 12, 2023 - 19:05:23\
Django version 4.2.5, using settings 'finchcollector.settings'\
Starting development server at http://127.0.0.1:8000/\
Quit the server with CONTROL-C.\
\
[12/Sep/2023 19:05:34] "GET / HTTP/1.1" 200 10664\
Not Found: /favicon.ico\
[12/Sep/2023 19:05:35] \cf6 "GET /favicon.ico HTTP/1.1" 404 2118\cf2 \
\'e7^C
\f1\b \cf7 \cb2 %
\f0\b0 \cf2 \cb1                                                                             \cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python3 manage.py migrate\
Traceback (most recent call last):\
  File "/opt/homebrew/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>\
    import psycopg as Database\
ModuleNotFoundError: No module named 'psycopg'\
\
During handling of the above exception, another exception occurred:\
\
Traceback (most recent call last):\
  File "/opt/homebrew/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 27, in <module>\
    import psycopg2 as Database\
ModuleNotFoundError: No module named 'psycopg2'\
\
During handling of the above exception, another exception occurred:\
\
Traceback (most recent call last):\
  File "/Users/rextsears/code/finchcollector/manage.py", line 22, in <module>\
    main()\
  File "/Users/rextsears/code/finchcollector/manage.py", line 18, in main\
    execute_from_command_line(sys.argv)\
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line\
    utility.execute()\
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute\
    django.setup()\
  File "/opt/homebrew/lib/python3.11/site-packages/django/__init__.py", line 24, in setup\
    apps.populate(settings.INSTALLED_APPS)\
  File "/opt/homebrew/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate\
    app_config.import_models()\
  File "/opt/homebrew/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models\
    self.models_module = import_module(models_module_name)\
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module\
    return _bootstrap._gcd_import(name[level:], package, level)\
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import\
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load\
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked\
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked\
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module\
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\
  File "/opt/homebrew/lib/python3.11/site-packages/django/contrib/auth/models.py", line 3, in <module>\
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager\
  File "/opt/homebrew/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 57, in <module>\
    class AbstractBaseUser(models.Model):\
  File "/opt/homebrew/lib/python3.11/site-packages/django/db/models/base.py", line 143, in __new__\
    new_class.add_to_class("_meta", Options(meta, app_label))\
  File "/opt/homebrew/lib/python3.11/site-packages/django/db/models/base.py", line 371, in add_to_class\
    value.contribute_to_class(cls, name)\
  File "/opt/homebrew/lib/python3.11/site-packages/django/db/models/options.py", line 243, in contribute_to_class\
    self.db_table, connection.ops.max_name_length()\
                   ^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__\
    return getattr(self._connections[self._alias], item)\
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__\
    conn = self.create_connection(alias)\
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/db/utils.py", line 193, in create_connection\
    backend = load_backend(db["ENGINE"])\
              ^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/db/utils.py", line 113, in load_backend\
    return import_module("%s.base" % backend_name)\
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module\
    return _bootstrap._gcd_import(name[level:], package, level)\
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>\
    raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")\
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module\
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ pip install psycopg2\
Collecting psycopg2\
  Downloading psycopg2-2.9.7.tar.gz (383 kB)\
     \cf8 \uc0\u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \u9473 \cf2  \cf9 383.5/383.5 kB\cf2  \cf5 1.8 MB/s\cf2  eta \cf10 0:00:00\cf2 \
  Preparing metadata (setup.py) ... done\
Building wheels for collected packages: psycopg2\
  Building wheel for psycopg2 (setup.py) ... done\
  Created wheel for psycopg2: filename=psycopg2-2.9.7-cp311-cp311-macosx_13_0_arm64.whl size=145724 sha256=67fdb90c250927f8ee266026690119c89f0f4cdc28ceb92ceaef492de4f9b772\
  Stored in directory: /Users/rextsears/Library/Caches/pip/wheels/ca/a2/1f/9f85470e2065e7a4089baa6c47cfa57a2f8f8e78e07390c5b4\
Successfully built psycopg2\
Installing collected packages: psycopg2\
Successfully installed psycopg2-2.9.7\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python3 manage.py migrate\

\f1\b \cf10 Operations to perform:
\f0\b0 \cf2 \

\f1\b   Apply all migrations: 
\f0\b0 admin, auth, contenttypes, sessions\

\f1\b \cf10 Running migrations:
\f0\b0 \cf2 \
  Applying contenttypes.0001_initial...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0001_initial...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying admin.0001_initial...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying admin.0002_logentry_remove_auto_add...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying admin.0003_logentry_add_action_flag_choices...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying contenttypes.0002_remove_content_type_name...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0002_alter_permission_name_max_length...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0003_alter_user_email_max_length...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0004_alter_user_username_opts...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0005_alter_user_last_login_null...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0006_require_contenttypes_0002...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0007_alter_validators_add_error_messages...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0008_alter_user_username_max_length...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0009_alter_user_last_name_max_length...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0010_alter_group_name_max_length...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0011_update_proxy_permissions...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying auth.0012_alter_user_first_name_max_length...
\f1\b \cf9  OK
\f0\b0 \cf2 \
  Applying sessions.0001_initial...
\f1\b \cf9  OK
\f0\b0 \cf2 \
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python manage.py makemigrations\
zsh: command not found: python\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python3 manage.py makemigrations\

\f1\b \cf10 Migrations for 'main_app':
\f0\b0 \cf2 \
  
\f1\b main_app/migrations/0001_initial.py
\f0\b0 \
    - Create model Finch\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python3 manage.py migrate\

\f1\b \cf10 Operations to perform:
\f0\b0 \cf2 \

\f1\b   Apply all migrations: 
\f0\b0 admin, auth, contenttypes, main_app, sessions\

\f1\b \cf10 Running migrations:
\f0\b0 \cf2 \
  Applying main_app.0001_initial...
\f1\b \cf9  OK
\f0\b0 \cf2 \
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python3 manage.py shell\
Python 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin\
Type "help", "copyright", "credits" or "license" for more information.\
(InteractiveConsole)\
>>> from main_app.models import Finch\
>>> \
>>> finch1 = Finch(name="House Finch", scientific_name="Haemorhous mexicanus", habitat="Urban and suburban areas")\
>>> finch2 = Finch(name="American Goldfinch", scientific_name="Spinus tristis", habitat="Open fields and gardens")\
>>> finch1.save()\
>>> finch2.save()\
>>> ^D\
now exiting InteractiveConsole...\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ mkdir finchcollector/main_app/templates\
mkdir: finchcollector/main_app: No such file or directory\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ ls\
db.sqlite3	finchcollector	main_app	manage.py\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ cd main_app\
\cf3 rextsears \cf4 ~/code/finchcollector/main_app \cf2  $ mkdir templates\
\cf3 rextsears \cf4 ~/code/finchcollector/main_app \cf2  $ cd templates\
\cf3 rextsears \cf4 ~/code/finchcollector/main_app/templates \cf2  $ touch finch_list.html\
\cf3 rextsears \cf4 ~/code/finchcollector/main_app/templates \cf2  $ touch finch_detail.html\
\cf3 rextsears \cf4 ~/code/finchcollector/main_app/templates \cf2  $ cd .\
\cf3 rextsears \cf4 ~/code/finchcollector/main_app/templates \cf2  $ cd .\
\cf3 rextsears \cf4 ~/code/finchcollector/main_app/templates \cf2  $ cd ..\
\cf3 rextsears \cf4 ~/code/finchcollector/main_app \cf2  $ cd ..\
\cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python3 manage.py runserver\
Watching for file changes with StatReloader\
Performing system checks...\
\
Exception in thread django-main-thread:\
Traceback (most recent call last):\
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner\
    self.run()\
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run\
    self._target(*self._args, **self._kwargs)\
  File "/opt/homebrew/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper\
    fn(*args, **kwargs)\
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run\
    self.check(display_num_errors=True)\
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check\
    all_issues = checks.run_checks(\
                 ^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks\
    new_errors = check(app_configs=app_configs, databases=databases)\
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config\
    return check_resolver(resolver)\
           ^^^^^^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver\
    return check_method()\
           ^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check\
    for pattern in self.url_patterns:\
                   ^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__\
    res = instance.__dict__[self.name] = self.func(instance)\
                                         ^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns\
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)\
                       ^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__\
    res = instance.__dict__[self.name] = self.func(instance)\
                                         ^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module\
    return import_module(self.urlconf_name)\
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module\
    return _bootstrap._gcd_import(name[level:], package, level)\
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import\
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load\
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked\
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked\
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module\
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\
  File "/Users/rextsears/code/finchcollector/finchcollector/urls.py", line 19, in <module>\
    from . import views\
ImportError: cannot import name 'views' from 'finchcollector' (/Users/rextsears/code/finchcollector/finchcollector/__init__.py)\
/Users/rextsears/code/finchcollector/finchcollector/urls.py changed, reloading.\
Watching for file changes with StatReloader\
Performing system checks...\
\
System check identified no issues (0 silenced).\
September 12, 2023 - 19:27:47\
Django version 4.2.5, using settings 'finchcollector.settings'\
Starting development server at http://127.0.0.1:8000/\
Quit the server with CONTROL-C.\
\
^C
\f1\b \cf7 \cb2 %
\f0\b0 \cf2 \cb1                                                                              \cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ python3 manage.py runserver\
Watching for file changes with StatReloader\
Performing system checks...\
\
System check identified no issues (0 silenced).\
September 12, 2023 - 19:28:02\
Django version 4.2.5, using settings 'finchcollector.settings'\
Starting development server at http://127.0.0.1:8000/\
Quit the server with CONTROL-C.\
\
^C
\f1\b \cf7 \cb2 %
\f0\b0 \cf2 \cb1                                                                              \cf3 rextsears \cf4 ~/code/finchcollector \cf2  $ \
}